services:
  apafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: apafana
    container_name: 'apafana-simple-app'
    build:
      args:
        grafana_image: apafana
        grafana_version: 1.0.0
        development: true
    volumes:
      - ./dist:/var/lib/grafana/plugins/apafana-simple-app
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/apafana-simple-app
    environment:
      GF_LOG_FILTERS: plugin.apafana-simple-app:debug
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: apafana-simple-app
