services:
  apafana:
    user: root
    container_name: 'apafana-simple-app'

    build:
      context: .
      args:
        grafana_image: apafana
        grafana_version: 1.0.0
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/apafana-simple-app
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/apafana-simple-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.apafana-simple-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: apafana-simple-app
